import dotenv from 'dotenv';

dotenv.config();

/** Prefer IPv4 DNS on Windows — reduces EAI_AGAIN for Deepgram/Supabase/Azure. */
import dns from 'dns';
dns.setDefaultResultOrder('ipv4first');

import './config/requireEnv';

import path from 'path';
import fs from 'fs';
import http from 'http';
import express from 'express';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import { WebSocketServer } from 'ws';
import { handleMediaStreamConnection } from './voice/mediaStreamHandler';
import cors from 'cors';
import connectDB from './config/db';
import authRoutes from './routes/authRoutes';
import legalRoutes from './routes/legalRoutes';
import userRoutes from './routes/userRoutes';
import tenantRoutes from './routes/tenantRoutes';
import dashboardRoutes from './routes/dashboardRoutes';
import uploadRoutes from './routes/uploadRoutes';
import voiceRoutes from './routes/voiceRoutes';
import voiceHealthRoutes from './routes/voiceHealthRoutes';
import voiceUtilityRoutes from './routes/voiceUtilityRoutes';
import voiceAdminRoutes from './routes/voiceAdminRoutes';
import browserVoiceRoutes from './routes/browserVoiceRoutes';
import agentRoutes from './routes/agentRoutes';
import chatRoutes from './routes/chatRoutes';
import subscriptionRoutes from './routes/subscriptionRoutes';
import catalogRoutes from './routes/catalogRoutes';
import orderRoutes from './routes/orderRoutes';
import leadRoutes from './routes/leadRoutes';
import analyticsRoutes from './routes/analyticsRoutes';
import campaignRoutes from './routes/campaignRoutes';
import outboundVoiceRoutes from './routes/outboundVoiceRoutes';
import documentRoutes from './routes/documentRoutes';
import connectorRoutes from './routes/connectorRoutes';
import slackOAuthRoutes from './routes/slackOAuthRoutes';
import platformRoutes from './routes/platformRoutes';
import publicChatRoutes from './routes/publicChatRoutes';
import { VOICE_MVP_CONTRACT } from './voice/voiceContract';
import { seedBuiltInTemplates } from './data/connectorTemplates';
import { startDigestScheduler } from './services/connectorService';
import { resumeAllRunning, checkScheduledCampaigns } from './voice/dialerManager';
import { requireInternalApiSecret } from './middleware/internalApiMiddleware';
import { internalGetCatalog, internalPostOrder, internalPostLead } from './controllers/internalAiController';
import { isEmailDeliveryConfigured } from './services/emailService';
import { isSlackInteractivityConfigured, isSlackOAuthConfigured } from './utils/slackEnv';
import { terminalLog } from './utils/terminalLog';
import { runVoiceStartupProbe } from './voice/voiceStartupProbe';
import { seedVoicePreviewSamples } from './services/voicePreviewService';
import { globalApiLimiter, notFoundHandler, globalErrorHandler } from './middleware/httpMiddleware';

const app = express();
const port = process.env.PORT || 3000;

app.use(helmet({
    crossOriginResourcePolicy: { policy: 'cross-origin' },
    contentSecurityPolicy: false,
}));
app.use(cookieParser());
app.use(globalApiLimiter);

app.use(cors({
    origin: [
        process.env.FRONTEND_URL || 'http://localhost:5173',
        'http://localhost:5173',
        'http://localhost:3000',
    ],
    credentials: true,
}));

// Raw body routes must come before express.json()
app.use('/api/subscription/webhook', express.raw({ type: 'application/json' }));
app.use('/api/slack/interactions', express.raw({ type: '*/*' }));

app.use(express.json());

const embedStaticRoot = path.join(process.cwd(), 'public', 'embed');
if (!fs.existsSync(embedStaticRoot)) {
    fs.mkdirSync(embedStaticRoot, { recursive: true });
}
app.use('/embed', express.static(embedStaticRoot));

/** Website chat widget + public chat API — permissive CORS so customer sites can call from browsers. */
const publicChatCors = cors({ origin: true, credentials: false, maxAge: 86400 });
app.use('/api/public', publicChatCors, publicChatRoutes);

const uploadsRoot = path.join(process.cwd(), 'uploads');
if (!fs.existsSync(uploadsRoot)) {
    fs.mkdirSync(uploadsRoot, { recursive: true });
}
app.use('/uploads', express.static(uploadsRoot));

// Temp audio files generated by Azure TTS — served to Twilio via <Play>.
// Files auto-delete after 2 minutes (see azureTtsService.ts).
const tempAudioRoot = path.join(process.cwd(), 'temp_audio');
if (!fs.existsSync(tempAudioRoot)) {
    fs.mkdirSync(tempAudioRoot, { recursive: true });
}
app.use('/api/audio/temp', express.static(tempAudioRoot));

app.use('/api/voice', express.urlencoded({ extended: false }));
app.use('/api/voice/browser', express.urlencoded({ extended: false }));
app.use('/api/voice/outbound', express.urlencoded({ extended: false }));

app.get('/health', (req, res) => {
    const emailOutbound = isEmailDeliveryConfigured();
    const slackOAuth = isSlackOAuthConfigured();
    res.json({
        status: 'ok',
        timestamp: new Date().toISOString(),
        emailOutbound,
        slackOAuthConfigured: slackOAuth,
        slackInteractivityConfigured: isSlackInteractivityConfigured(),
        voice: {
            mvpVersion: VOICE_MVP_CONTRACT.version,
            loop: VOICE_MVP_CONTRACT.loop,
            channels: VOICE_MVP_CONTRACT.channels,
        },
    });
});

// Routes
app.use('/api/auth', authRoutes);
app.use('/api/legal', legalRoutes);
app.use('/api/user', userRoutes);
app.use('/api/tenant', tenantRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/upload', uploadRoutes);
// Sub-routes MUST be mounted before /api/voice so they are not
// caught by the Twilio signature validation on the parent voiceRoutes.
app.use('/api/voice/browser', browserVoiceRoutes);
app.use('/api/voice/outbound', outboundVoiceRoutes);
app.use('/api/voice/util', voiceUtilityRoutes);
app.use('/api/voice', voiceHealthRoutes);
app.use('/api/voice', voiceRoutes);
app.use('/api/voice-admin', voiceAdminRoutes);
app.use('/api/agents', agentRoutes);
app.use('/api/catalog', catalogRoutes);
app.use('/api/orders', orderRoutes);
app.use('/api/leads', leadRoutes);
app.use('/api/analytics', analyticsRoutes);
app.use('/api/campaigns', campaignRoutes);
app.use('/api/chat', chatRoutes);
app.use('/api/subscription', subscriptionRoutes);
app.use('/api/documents', documentRoutes);
app.use('/api/connectors', connectorRoutes);
app.use('/api/slack', slackOAuthRoutes);

app.use('/api/platform', platformRoutes);

// AI service integrations - use INTERNAL_API_SECRET; send X-Internal-Secret (or Bearer) from ai_service
app.get('/api/internal/catalog', requireInternalApiSecret, internalGetCatalog);
app.post('/api/internal/orders', requireInternalApiSecret, internalPostOrder);
app.post('/api/internal/leads', requireInternalApiSecret, internalPostLead);

app.use(notFoundHandler);
app.use(globalErrorHandler);

async function runPostConnectStartup(): Promise<void> {
    await new Promise<void>((resolve) => setImmediate(resolve));
    await seedBuiltInTemplates();
    void seedVoicePreviewSamples();
    if (process.env.ELVA_SKIP_LISTEN === '1') {
        return;
    }
    startDigestScheduler();
    resumeAllRunning().catch(err => console.error('[STARTUP] dialerManager resume error:', err?.message));
    setInterval(() => {
        checkScheduledCampaigns().catch(err => console.error('[SCHEDULER] checkScheduled error:', err?.message));
    }, 60_000);
    checkScheduledCampaigns().catch(() => {});
}

function listenHttp(): void {
    const httpServer = http.createServer(app);

    if (process.env.ENABLE_MEDIA_STREAMS === 'true') {
        const wss = new WebSocketServer({ server: httpServer, path: '/api/voice/stream' });
        wss.on('connection', (ws, req) => {
            const url = new URL(req.url || '', 'http://localhost');
            const callSid = url.searchParams.get('callSid') || '';
            const token = url.searchParams.get('token') || '';
            const type = (url.searchParams.get('type') || 'inbound') as
                | 'inbound'
                | 'outbound'
                | 'browser';

            handleMediaStreamConnection(ws, callSid, type, token);
        });
        terminalLog.voice('STREAM', 'WebSocket ready at /api/voice/stream');
    }

    httpServer.listen(port, () => {
        terminalLog.banner('ELVA Backend');
        terminalLog.ok('Server', `Listening on port ${port}`);
        terminalLog.info('Email', isEmailDeliveryConfigured() ? 'SendGrid configured' : 'SendGrid disabled');
        const slackOAuth = isSlackOAuthConfigured();
        const slackIx = isSlackInteractivityConfigured();
        terminalLog.info('Slack OAuth', slackOAuth ? 'Configured' : 'Disabled');
        if (slackOAuth) {
            terminalLog.row('Slack interactivity', slackIx ? 'Configured' : 'Needs SLACK_SIGNING_SECRET', slackIx);
        }
        void runVoiceStartupProbe().catch(err => {
            terminalLog.err('Voice probe', err instanceof Error ? err.message : String(err));
        });
    });
}

async function bootstrap(): Promise<void> {
    await connectDB();
    await runPostConnectStartup();
    if (process.env.ELVA_SKIP_LISTEN !== '1') {
        listenHttp();
    }
}

void bootstrap().catch(err => {
    terminalLog.err('Startup', err instanceof Error ? err.message : String(err));
    process.exit(1);
});

export default app;
